### ISSUE TITLE
[Bug] Improve error logging and catch more exceptions

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-explorer#101]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**

The Docker container logs regularly seem to contain entries of the form shown below. This often happens when the Explorer is idle. These errors should be caught and handled appropriately, and if necessary something more meaningful logged. It's unclear if these exceptions represent a bug, or an expected exception. In either case the root cause should be handled better and the logs should be cleaner. Logging exceptions implies a bug (whether true or not).

```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at getRequestObjects (/graph-explorer/packages/graph-explorer-proxy-server/node-server.js:118:13)
    at retryFetch (/graph-explorer/packages/graph-explorer-proxy-server/node-server.js:63:24)
    at /graph-explorer/packages/graph-explorer-proxy-server/node-server.js:165:24
    at Layer.handle [as handle_request] (/graph-explorer/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/graph-explorer/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/graph-explorer/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/graph-explorer/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
No endpoint passed
```

From time to time the logs also contain a lot of entries as shown below. This is not useful. The message should either be something meaningful/actionable, or not logged at all.

```
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
Response ok
```
The notes above cover "server side" logging done by the Docker container. The logging done in the browser could, and should, also be expanded. Trouble shooting issues will be much easier with more extensive logging.

**Comment by cubeddu** [comment]
@krlawrence Logging has been added to repo.
