### ISSUE TITLE
[Bug] Graph Explorer UI crashes when previewing node details under search

### ISSUE THREAD

**Issue by michaelnchin** [aws/graph-explorer#165]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
When attempting to click on the body (NOT the plus sign/"Add to canvas") of a node listed under the search UI, the Graph Explorer UI will sometimes crash and go blank.

Browser console error on Firefox:
```
TypeError: Cannot read properties of undefined (reading 'el')
    at f (index-c8b857f2.js:1430:102652)
    at p (index-c8b857f2.js:1430:102897)
    at jb.<anonymous> (index-c8b857f2.js:1430:108195)
    at index-c8b857f2.js:1430:52791
    at Array.forEach (<anonymous>)
    at index-c8b857f2.js:1430:52777
    at Array.forEach (<anonymous>)
    at jb.emit (index-c8b857f2.js:1430:52597)
    at jb.t3t [as checkOverflow] (index-c8b857f2.js:1430:88806)
    at jb.tkt [as updateSlides] (index-c8b857f2.js:1430:57513)
```

Browser console error on Chrome:
```
Uncaught TypeError: t.params.pagination is undefined
    f https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    p https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    o3t https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    emit https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    emit https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    emit https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    t3t https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    tkt https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    init https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    s3t https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    tRe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:1430
    PVe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:39
    MVe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    unstable_runWithPriority https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:26
    SS https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    Jx https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    sJ https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:39
    qTe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    unstable_runWithPriority https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:26
    SS https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    qTe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    x0 https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    fTe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    _Ue https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    DTe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    Lve https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    MTe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    MTe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:37
    one https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    qVe https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    gF https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    render https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:41
    <anonymous> https://aws-neptune-explorer-301-prod.notebook.us-west-2.sagemaker.aws/proxy/9250/explorer/assets/index-c8b857f2.js:4322

```

 - OS: Amazon Linux 2 (SageMaker Notebook)
 - Browser: Chrome and Firefox
 - Graph Explorer Version: 1.3.0
 - Graph Database & Version: Neptune 1.2.1.0

**To Reproduce**
1. Open the Graph Explorer UI.
2. Click on the search bar at the top of the page to open the search UI.
3. In the search UI, click in the center of any node listed on the left hand column.
4. Observe the bug.

**Comment by michaelnchin** [comment]
This issue appears specific to Graph Explorer deployments via Neptune Notebooks or ECS.
